class Antistasi
{
    class AI
    {
        class AAFKilledEH {};
        class AILoadInfo {};
        class airDrop {};
        class AIReactOnKill {};
        class airstrike {};
        class artillery {};
        class artySupport{};
        class assaultBuilding {};
        class attackAAF {};
        class attackDrillAI{};
        class autoHeal {};
        class autoLoot {};
        class autoRearm {};
        class bombingRun {};
        class canConquer{};
        class canFight {};
        class captiveAI {};
        class cover {};
        class coverWithSmoke {};
        class defendDrillAI {};
        class destroyBuilding {};
        class doFlank {};
        class enemyList {};
        class enemySides{};
        class fastrope {};
        class findGroupMedic {};
        class findSafeRoadToUnload{};
        class guardDog {};
        class hasRadio {};
        class hayLOS {};
        class hideInBuilding {};
        class immuneConvoy {};
        class interrogate {};
        class isBuildingPosition {};
        class isInRoof {};
        class isWindowPosition {};
        class landThreatEval {};
        class liberatePOW {};
        class liberateRefugee {};
        class medicPlayer {};
        class mineSweep {};
        class mortarDrill {};
        class mortarSupport {};
        class mortyAI {};
        class napalm {};
        class napalmDamage {};
        class nearbyEnemy {};
        class openVehDoors {};
        class rearmCall {};
        class recallGroup {};
        class smokeCoverAuto {};
        class staticAutoT {};
        class staticMGDrill {};
        class suppressiveFire {};
        class surrenderAction {};
        class typeOfSoldier {};
        class undercoverAI {};
        class unitGetToCover {};
        class VANTInfo {};
        class vehicleMarkers {};
    };
    class Equipment {
        class AAFCrate {};
        class ACEpvpReDress {};
        class arsenalManage {};
        class CSATCrate {};
        class emptyNearbyVehicles {};
        class munitionTransfer {};
        class NATOCrate {};
        class randomRifle {};
        class RHSdress {};
        class transferEquipmentToVehicle {};
    };
    class Missions
    {
        class assassinateOfficer {};
        class assassinateSpecOp {};
        class assassinateTraitor {};
        class attackHQ {};
        class conquerOutpost {};
        class deleteTask {};
        class destroyAntenna {};
        class destroyHeli {};
        class destroyVehicle {};
        class interceptConvoy {};
        class logisticsAmmo {};
        class logisticsBank {};
        class logisticsSupplies {};
        class missionGiver {};
        class missionRequest {};
        class missionRequestAuto {};
        class rescuePrisoners {};
        class rescueRefugees {};
        class sabotageRepairs {};
        class spawnMissionGiver {};
        class underAttack {};
        class updateTask {};
    };
    class Player
    {
        class assignStavros {};
        class briefing {};
        class cityInfo {};
        class clearForest {};
        class commResign {};
        class donateMoney {};
        class fastTravelRadio {};
        class FIARadio {};
        class flagAction{};
        class garage {};
        class garageVehicle {};
        class garrisonInfo {};
        class healAndRepair {};
        class hotkeys {};
        class initPlayerLocal {};
        class intelFound {};
        class isMember {};
        class memberAdd {};
        class membersList {};
        class moveHQ {};
        class moveHQObject{};
        class mrkWin {};
        class music {};
        class NATOFT {};
        class nonMemberDistance{};
        class onOffLamp {};
        class onPlayerDisconnect {};
        class onPlayerRespawn{};
        class outpostDialog {};
        class pickHQLocation {};
        class playerHasBeenPvPCheck {};
        class playerMarkers{};
        class playerScoreAdd{};
        class punishment {};
        class radioJam{};
        class rankMP{};
        class rebuildAssets{};
        class reinitY{};
        class resourcecheckSkipTime{};
        class resourcesPlayer{};
        class revealToPlayer{};
        class sellVehicle{};
        class skipTime {};
        class statistics {};
        class stavrosInit {};
        class stavrosSteal {};
        class tags {};
        class tierCheck {};
        class undercover {};
        class unitTraits {};
        class unlockVehicle {};
        class vip {};
    };
    class Revive
    {
        class actionRevive{};
        class carry{};
        class fatalWound{};
        class handleDamage{};
        class handleDamageAAF{};
        class initRevive {};
        class isMedic {};
        class respawn {};
        class unconscious {};
        class unconsciousAAF {};
    };
    class System
    {
        class addHC {};
        class addTimeForIdle {};
        class advancedTowingInit{};
        class blackout {};
        class buildHQ {};
        class citiesToCivPatrol {};
        class citySupportChange {};
        class commsMP {};
        class createOutpostFIA {};
        class createRoadblock {};
        class deleteRoadblock {};
        class destroyCity {};
        class distancesFor {};
        class distanceUnits {};
        class findBasesForConvoy{};
        class findNearestGoodRoad{};
        class fogCheck {};
        class garbageCleaner {};
        class getLocations{};
        class init {};
        class initPetros {};
        class initFuncs {};
        class initServer{};
        class initVar {};
        class initZones {};
        class isFrontline {};
        class isTheSameIsland {};
        class loadAccount {};
        class locator {};
        class markerChange{};
        class markerUpdate{}
        class modBlacklist{};
        class numericRank {};
        class patrolDestinations {};
        class powerCheck {};
        class powerReorg {};
        class prestige {};
        class radioCheck {};
        class resourceCheck {};
        class resourcesFIA {};
        class returnMuzzle {};
        class roadsDB {};
        class roadsDBAltis {};
        class saveFuncs {};
        class saveLoop {};
        class scheduler {};
        class sizeMarker {};
        class tempMoveMarker{};
        class timingCA {};
        class zoneCheck {};         
    };
    class Upsmon {
        class initUpsmon {};
        class upsmon {};
        class upsmonCreateGroup {};
    }
};